# Generated by Django 4.2.7 on 2023-11-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_rename_meter_reading_recyclingoperation_meter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='meter_ID',
            field=models.CharField(max_length=100),
        ),
    ]
