# Generated by Django 4.2.7 on 2023-11-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_alter_electricity_meter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingoperation',
            name='total_electricity_variance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
