# Generated by Django 4.2.7 on 2023-11-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity',
            name='total_electricity_variance',
        ),
    ]
