# Generated by Django 4.2.7 on 2023-11-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='previous_meter_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
