# Generated by Django 4.2.7 on 2023-11-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_electricity_previous_meter_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity',
            name='standard_electricity_cost',
        ),
        migrations.AddField(
            model_name='recyclingoperation',
            name='standard_electricity_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
