# Generated by Django 4.2.7 on 2023-11-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_remove_electricity_standard_electricity_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity',
            name='electricity_variance',
        ),
        migrations.AddField(
            model_name='recyclingoperation',
            name='electricity_variance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
