# Generated by Django 4.2.7 on 2023-11-26 02:39

from django.db import migrations, models
import django.db.models.deletion
import operations.models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0032_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlakesCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_id', models.CharField(max_length=100)),
                ('cost_of_washing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_of_transport', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlakesIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('flakes_type', models.CharField(max_length=255, validators=[operations.models.validate_no_numbers])),
                ('flakes_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PelletsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pellets_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.flakescost')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.flakesin')),
            ],
        ),
    ]
