# Generated by Django 4.2.7 on 2023-11-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0035_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
